import { Component, OnInit, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from '../../core/services/api.service';
import { NotificationService } from '../../core/services/notification.service';
import { Modlist, ModEntry } from '../../shared/models/mod.model';
import { HardwareBadgeComponent } from '../../shared/components/hardware-badge/hardware-badge.component';

@Component({
  selector: 'app-modlist',
  standalone: true,
  imports: [HardwareBadgeComponent],
  template: `
    <div class="modlist-page">
      @if (loading()) {
        <div class="loading">
          <div class="spinner"></div>
          <p>Loading modlist...</p>
        </div>
      } @else if (modlist()) {
        <div class="modlist-header">
          <div>
            <h1>Your Modlist</h1>
            <p class="subtitle">
              {{ modlist()!.entries.length }} mods
              @if (modlist()!.hardware_tier) {
                &middot; <app-hardware-badge [tier]="modlist()!.hardware_tier!" />
              }
              @if (modlist()!.llm_provider) {
                &middot; Generated by {{ modlist()!.llm_provider }}
              }
            </p>
          </div>
          <div class="header-actions">
            <button class="btn-primary" (click)="downloadAll()">
              Download All
            </button>
          </div>
        </div>

        <div class="mod-list">
          @for (entry of modlist()!.entries; track entry.mod_id; let i = $index) {
            <div class="mod-card" [class.disabled]="!entry.enabled">
              <div class="mod-order">{{ entry.load_order || i + 1 }}</div>
              <div class="mod-info">
                <div class="mod-header">
                  <h3>{{ entry.name }}</h3>
                  @if (entry.author) {
                    <span class="mod-author">by {{ entry.author }}</span>
                  }
                </div>
                @if (entry.summary) {
                  <p class="mod-summary">{{ entry.summary }}</p>
                }
                @if (entry.reason) {
                  <p class="mod-reason">{{ entry.reason }}</p>
                }
              </div>
              <div class="mod-actions">
                <span class="status-badge" [class]="'status-' + entry.download_status">
                  {{ entry.download_status }}
                </span>
                <button
                  class="btn-toggle"
                  [class.active]="entry.enabled"
                  (click)="toggleMod(entry)"
                >
                  {{ entry.enabled ? 'ON' : 'OFF' }}
                </button>
              </div>
            </div>
          }
        </div>

        @if (modlist()!.entries.length === 0) {
          <div class="empty-state">
            <p>No mods in this modlist yet.</p>
            <button class="btn-secondary" (click)="goToSetup()">Create New Modlist</button>
          </div>
        }
      } @else {
        <div class="empty-state">
          <p>Modlist not found.</p>
          <button class="btn-secondary" (click)="goToSetup()">Create New Modlist</button>
        </div>
      }
    </div>
  `,
  styles: [`
    .modlist-page { max-width: 800px; margin: 0 auto; padding: 2rem; }

    .loading {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 4rem;
      gap: 1rem;
      color: var(--color-text-muted);
    }
    .spinner {
      width: 40px;
      height: 40px;
      border: 3px solid var(--color-bg-elevated);
      border-top-color: var(--color-primary);
      border-radius: 50%;
      animation: spin 0.8s linear infinite;
    }
    @keyframes spin { to { transform: rotate(360deg); } }

    .modlist-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 2rem;
    }
    h1 { font-size: 1.75rem; font-weight: 700; margin: 0 0 0.5rem; }
    .subtitle {
      color: var(--color-text-muted);
      display: flex;
      align-items: center;
      gap: 0.5rem;
      flex-wrap: wrap;
      margin: 0;
    }

    .btn-primary {
      background: var(--color-primary);
      color: white;
      padding: 0.625rem 1.5rem;
      border-radius: 8px;
      font-weight: 600;
      border: none;
      cursor: pointer;
      font-family: inherit;
      font-size: 0.875rem;
    }
    .btn-primary:hover { background: var(--color-primary-hover); }
    .btn-secondary {
      background: transparent;
      border: 1px solid var(--color-border);
      color: var(--color-text);
      padding: 0.625rem 1.5rem;
      border-radius: 8px;
      font-weight: 500;
      cursor: pointer;
      font-family: inherit;
      font-size: 0.875rem;
    }
    .btn-secondary:hover { background: var(--color-bg-elevated); }

    .mod-list {
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
    }

    .mod-card {
      background: var(--color-bg-card);
      border: 1px solid var(--color-border);
      border-radius: 10px;
      padding: 1rem 1.25rem;
      display: flex;
      align-items: flex-start;
      gap: 1rem;
      transition: opacity 0.2s, border-color 0.2s;
    }
    .mod-card:hover { border-color: var(--color-primary); }
    .mod-card.disabled { opacity: 0.5; }

    .mod-order {
      min-width: 28px;
      height: 28px;
      background: var(--color-bg-elevated);
      border-radius: 6px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 0.75rem;
      font-weight: 600;
      color: var(--color-text-muted);
      flex-shrink: 0;
      margin-top: 2px;
    }

    .mod-info { flex: 1; min-width: 0; }
    .mod-header { display: flex; align-items: baseline; gap: 0.5rem; flex-wrap: wrap; }
    .mod-header h3 { font-size: 0.95rem; font-weight: 600; margin: 0; }
    .mod-author { font-size: 0.8rem; color: var(--color-text-muted); }
    .mod-summary { font-size: 0.825rem; color: var(--color-text-muted); margin: 0.375rem 0 0; line-height: 1.4; }
    .mod-reason {
      font-size: 0.775rem;
      color: var(--color-primary);
      margin: 0.25rem 0 0;
      font-style: italic;
    }

    .mod-actions {
      display: flex;
      flex-direction: column;
      align-items: flex-end;
      gap: 0.5rem;
      flex-shrink: 0;
    }

    .status-badge {
      font-size: 0.7rem;
      font-weight: 600;
      text-transform: uppercase;
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
    }
    .status-pending { background: #78350f; color: #fcd34d; }
    .status-downloading { background: #1e3a5f; color: #60a5fa; }
    .status-complete { background: #14532d; color: #86efac; }
    .status-failed { background: #7f1d1d; color: #fca5a5; }

    .btn-toggle {
      background: var(--color-bg-elevated);
      border: 1px solid var(--color-border);
      color: var(--color-text-muted);
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      cursor: pointer;
      font-size: 0.7rem;
      font-weight: 600;
      font-family: inherit;
    }
    .btn-toggle.active {
      background: var(--color-accent-green);
      color: white;
      border-color: var(--color-accent-green);
    }

    .empty-state {
      text-align: center;
      padding: 4rem;
      color: var(--color-text-muted);
    }
    .empty-state p { margin-bottom: 1rem; }
  `],
})
export class ModlistComponent implements OnInit {
  modlist = signal<Modlist | null>(null);
  loading = signal(true);

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private api: ApiService,
    private notifications: NotificationService,
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.api.getModlist(id).subscribe({
        next: (modlist) => {
          this.modlist.set(modlist);
          this.loading.set(false);
        },
        error: () => {
          this.loading.set(false);
          this.notifications.error('Failed to load modlist');
        },
      });
    } else {
      this.loading.set(false);
    }
  }

  toggleMod(entry: ModEntry): void {
    entry.enabled = !entry.enabled;
  }

  downloadAll(): void {
    const ml = this.modlist();
    if (!ml) return;

    const enabledModIds = ml.entries
      .filter((e) => e.enabled && e.mod_id)
      .map((e) => e.mod_id!);

    this.api.startDownloads(ml.id, enabledModIds).subscribe({
      next: () => {
        this.notifications.success('Downloads started!');
        this.router.navigate(['/downloads'], { queryParams: { modlist: ml.id } });
      },
      error: () => {
        this.notifications.error('Failed to start downloads');
      },
    });
  }

  goToSetup(): void {
    this.router.navigate(['/setup']);
  }
}
