"""Seed data for games, playstyles, and curated mods."""

GAMES = [
    {
        "name": "Skyrim Special Edition",
        "slug": "skyrimse",
        "nexus_domain": "skyrimspecialedition",
        "image_url": None,
    },
    {
        "name": "Fallout 4",
        "slug": "fallout4",
        "nexus_domain": "fallout4",
        "image_url": None,
    },
]

PLAYSTYLES = {
    "skyrimse": [
        {
            "name": "Vanilla+",
            "slug": "vanilla-plus",
            "description": "Keep the core Skyrim experience with quality-of-life improvements, bug fixes, and subtle visual upgrades.",
            "icon": "V+",
        },
        {
            "name": "Survival / Hardcore",
            "slug": "survival",
            "description": "Hunger, cold, fatigue, and deadly encounters. Transform Skyrim into a harsh survival experience.",
            "icon": "SV",
        },
        {
            "name": "Combat Overhaul",
            "slug": "combat",
            "description": "Revamp melee, archery, and magic combat with new animations, dodge mechanics, and enemy AI.",
            "icon": "CB",
        },
        {
            "name": "Magic / Spellcaster",
            "slug": "magic",
            "description": "Expand the magic system with hundreds of new spells, enchantments, and magical mechanics.",
            "icon": "MG",
        },
        {
            "name": "Visual / Graphics",
            "slug": "visual",
            "description": "Push Skyrim's visuals to the limit with ENB presets, texture packs, weather overhauls, and lighting mods.",
            "icon": "GX",
        },
        {
            "name": "Immersion / Roleplay",
            "slug": "immersion",
            "description": "Deep roleplaying with NPC overhauls, dialogue expansion, economy changes, and world-building mods.",
            "icon": "RP",
        },
    ],
    "fallout4": [
        {
            "name": "Vanilla+",
            "slug": "vanilla-plus",
            "description": "Improve the base Fallout 4 experience with essential fixes, UI improvements, and balanced tweaks.",
            "icon": "V+",
        },
        {
            "name": "Survival / Hardcore",
            "slug": "survival",
            "description": "Real needs, harder combat, scarce resources, and a truly post-apocalyptic survival experience.",
            "icon": "SV",
        },
        {
            "name": "Settlement Builder",
            "slug": "settlement",
            "description": "Supercharge settlement building with expanded objects, snapping, power tools, and city-scale builds.",
            "icon": "SB",
        },
        {
            "name": "Combat / Tactical",
            "slug": "combat",
            "description": "Realistic ballistics, weapon overhauls, new animations, tactical AI, and cover-based combat.",
            "icon": "CB",
        },
        {
            "name": "Visual / Graphics",
            "slug": "visual",
            "description": "Transform the Commonwealth with high-resolution textures, lighting overhauls, weather, and ENB.",
            "icon": "GX",
        },
        {
            "name": "Sim Settlements",
            "slug": "sim-settlements",
            "description": "Let settlers build their own homes and shops. Cities grow organically with Sim Settlements framework.",
            "icon": "SS",
        },
    ],
}

# Curated mod database for Skyrim SE
# Each entry: (nexus_mod_id, name, author, summary, category, performance_impact, vram_requirement_mb)
SKYRIM_MODS = [
    # === Essential / Vanilla+ (all tiers) ===
    (266, "Unofficial Skyrim Special Edition Patch", "Arthmoor",
     "Comprehensive bug fix compilation for Skyrim SE.",
     "Bug Fixes", "minimal", None),
    (1651, "SSE Engine Fixes", "aers",
     "Engine-level bug fixes and memory patches for Skyrim SE.",
     "Bug Fixes", "minimal", None),
    (32444, "Address Library for SKSE Plugins", "meh321",
     "Shared library of memory addresses used by SKSE plugins.",
     "Modders Resources", "minimal", None),
    (12604, "SkyUI", "SkyUI Team",
     "Elegant, PC-friendly interface with mod configuration menu.",
     "User Interface", "minimal", None),
    (19246, "Static Mesh Improvement Mod", "Brumbek",
     "Improved 3D models for architecture, clutter, landscape, and more.",
     "Models and Textures", "low", 512),
    (18830, "A Quality World Map", "IcePenguin",
     "High quality world map with roads and detailed terrain.",
     "User Interface", "minimal", None),
    (3863, "Cutting Room Floor", "Arthmoor",
     "Restores content cut from the final game release.",
     "Gameplay", "minimal", None),
    (21294, "Weapons Armor Clothing and Clutter Fixes", "kryptopyr",
     "Fixes bugs and inconsistencies for items in Skyrim.",
     "Bug Fixes", "minimal", None),

    # === Survival ===
    (28029, "Frostfall - Hypothermia Camping Survival", "Chesko",
     "Comprehensive cold weather survival system with camping.",
     "Immersion", "minimal", None),
    (38571, "Campfire - Complete Camping System", "Chesko",
     "Portable camping gear, tents, fires, and skill system.",
     "Immersion", "minimal", None),
    (50251, "Sunhelm Survival and Needs", "colinswrath",
     "Lightweight survival mod covering hunger, fatigue, and cold.",
     "Immersion", "minimal", None),
    (2018, "Hunterborn", "unuroboros",
     "Expanded hunting and foraging mechanics for animal harvesting.",
     "Gameplay", "minimal", None),

    # === Combat ===
    (15170, "Wildcat - Combat of Skyrim", "EnaiSiaion",
     "Lethal and dynamic combat overhaul with injuries and timed block.",
     "Combat", "minimal", None),
    (99233, "Valhalla Combat", "dTry",
     "Modernized combat with timed block, stamina management, and execution.",
     "Combat", "minimal", None),
    (2700, "TK Dodge RE", "tktk",
     "Responsive dodge roll mechanic for melee and ranged combat.",
     "Combat", "minimal", None),
    (53148, "True Directional Movement", "Ersh",
     "Target lock, directional movement, and headtracking.",
     "Combat", "minimal", None),
    (76843, "Precision - Accurate Melee Collisions", "Ersh",
     "Physics-based melee hit detection and weapon trails.",
     "Combat", "minimal", None),

    # === Magic ===
    (9137, "Apocalypse - Magic of Skyrim", "EnaiSiaion",
     "Adds 155 new spells across all schools of magic.",
     "Magic", "minimal", None),
    (104440, "Mysticism - A Magic Overhaul", "SimonMagus",
     "Rebalances and expands vanilla magic with new spells and effects.",
     "Magic", "minimal", None),
    (39199, "Triumvirate - Mage Archetypes", "EnaiSiaion",
     "Adds unique spells and powers for mage character archetypes.",
     "Magic", "minimal", None),
    (80660, "Odin - Skyrim Magic Overhaul", "EnaiSiaion",
     "Overhauls vanilla spells and adds new ones with improved effects.",
     "Magic", "minimal", None),

    # === Visual - Low/Mid tier ===
    (2347, "Skyrim Flora Overhaul", "vurt",
     "Overhauls trees, plants, and grass with new models and textures.",
     "Models and Textures", "medium", 1024),
    (607, "Noble Skyrim Mod HD-2K", "Shutt3r",
     "Complete texture pack covering architecture, landscape, and more.",
     "Models and Textures", "medium", 2048),
    (17802, "Realistic Water Two", "isoku",
     "Overhauls water with realistic textures, flow, and effects.",
     "Models and Textures", "low", 256),
    (2572, "Climates Of Tamriel", "JJC71",
     "Weather and lighting overhaul with hundreds of new weather types.",
     "Environment", "low", 256),

    # === Visual - High/Ultra tier ===
    (1089, "ENB Series - Rudy ENB", "Rudy102",
     "Photorealistic ENB preset with advanced lighting and effects.",
     "ENB Preset", "extreme", 4096),
    (42521, "Obsidian Weathers and Seasons", "Obsidian",
     "Modern weather overhaul with seasons and dynamic weather.",
     "Environment", "low", 256),
    (68292, "Lux - Via", "Sukolgaming",
     "Complete lighting overhaul for road and bridge lighting.",
     "Environment", "low", 128),
    (113588, "Skyland AIO", "Skyland",
     "All-in-one texture pack covering landscapes, architecture, and dungeons.",
     "Models and Textures", "medium", 2048),

    # === Immersion / Roleplay ===
    (36334, "Relationship Dialogue Overhaul", "CloudedTruth",
     "Thousands of new lines of dialogue for followers and NPCs.",
     "Immersion", "minimal", None),
    (29969, "Immersive Citizens - AI Overhaul", "Arnaud dOrchymont",
     "Overhauls NPC AI for more realistic schedules and behavior.",
     "NPC", "minimal", None),
    (11811, "Ordinator - Perks of Skyrim", "EnaiSiaion",
     "Overhauls the perk tree with 469 new perks across all skill trees.",
     "Gameplay", "minimal", None),
    (1334, "Interesting NPCs", "Kris Takahashi",
     "Adds over 250 fully voiced NPCs with quests and follower options.",
     "NPC", "low", 512),
    (68000, "JK Skyrim", "Jkrojmal",
     "Overhauls all major cities and towns with new architecture and details.",
     "Environment", "medium", 1024),
]

# Curated mod database for Fallout 4
FALLOUT4_MODS = [
    # === Essential / Vanilla+ ===
    (4598, "Unofficial Fallout 4 Patch", "Arthmoor",
     "Comprehensive bug fix compilation for Fallout 4.",
     "Bug Fixes", "minimal", None),
    (102, "Armorsmith Extended", "Gambit77",
     "Full armor customization with layered system and workbench crafting.",
     "Crafting", "minimal", None),
    (4472, "Full Dialogue Interface", "Cirosan",
     "Shows the full text of dialogue options instead of abbreviated summaries.",
     "User Interface", "minimal", None),
    (6091, "Improved Map with Visible Roads", "mm137",
     "Better world map with visible roads and colored regions.",
     "User Interface", "minimal", None),
    (27602, "Sim Settlements 2", "kinggath",
     "Settlers build their own homes, shops, and defenses automatically.",
     "Settlement", "low", 512),
    (3841, "Spring Cleaning", "Sp4rkR4t",
     "Enables scrapping of all static objects in settlements.",
     "Settlement", "minimal", None),

    # === Survival ===
    (12511, "Horizon", "Zawinul",
     "Complete survival overhaul covering loot, crafting, combat, and progression.",
     "Gameplay Overhaul", "minimal", None),
    (37793, "Gas Masks of the Wasteland", "lKocMoHaBTl",
     "Environmental hazards require gas masks and filters to survive.",
     "Immersion", "minimal", None),

    # === Combat / Tactical ===
    (15429, "Arbitration - Combat AI", "Greslin",
     "Smarter enemy AI with flanking, grenades, and realistic detection.",
     "Combat", "minimal", None),
    (10737, "Better Locational Damage", "Zzyxzz",
     "Realistic damage based on hit location with armor penetration.",
     "Combat", "minimal", None),
    (3177, "Enhanced Blood Textures", "dDefinder",
     "Improved blood textures, splatter, and wound effects.",
     "Models and Textures", "low", 256),

    # === Visual ===
    (217, "Vivid Fallout - All in One", "Hein84",
     "Complete landscape texture overhaul for the Commonwealth.",
     "Models and Textures", "medium", 2048),
    (34346, "PhyLight - Physics based Relighting", "Rez de Chaussee",
     "Realistic lighting overhaul with physically based rendering.",
     "Environment", "medium", 1024),
    (1355, "True Storms - Wasteland Edition", "fadingsignal",
     "Intense weather with radiation storms, heavy fog, and dust storms.",
     "Environment", "low", 256),

    # === Settlement ===
    (7683, "Place Everywhere", "TheLich",
     "Remove placement restrictions for complete building freedom.",
     "Settlement", "minimal", None),
    (30396, "Workshop Framework", "kinggath",
     "Framework for advanced settlement scripting and management.",
     "Settlement", "minimal", None),
]

# Compatibility rules: (mod_name_1, mod_name_2, rule_type, notes)
SKYRIM_COMPATIBILITY = [
    ("Wildcat - Combat of Skyrim", "Valhalla Combat", "conflicts",
     "Both overhaul combat mechanics. Choose one."),
    ("Climates Of Tamriel", "Obsidian Weathers and Seasons", "conflicts",
     "Both overhaul weather. Choose one."),
    ("Apocalypse - Magic of Skyrim", "Ordinator - Perks of Skyrim", "patch_available",
     "Use Apocalypse-Ordinator Compatibility Patch for full integration."),
    ("True Directional Movement", "Precision - Accurate Melee Collisions", "load_after",
     "Load Precision after TDM for proper hit detection."),
    ("Frostfall - Hypothermia Camping Survival", "Campfire - Complete Camping System", "requires",
     "Frostfall requires Campfire as a framework."),
    ("SkyUI", "Frostfall - Hypothermia Camping Survival", "requires",
     "Frostfall requires SkyUI for the MCM configuration menu."),
    ("Noble Skyrim Mod HD-2K", "Skyland AIO", "conflicts",
     "Both are full texture packs. Choose one based on your preference."),
]

FALLOUT4_COMPATIBILITY = [
    ("Horizon", "Better Locational Damage", "conflicts",
     "Horizon includes its own damage system. Do not combine."),
    ("Sim Settlements 2", "Workshop Framework", "requires",
     "Sim Settlements 2 requires Workshop Framework."),
    ("Sim Settlements 2", "Place Everywhere", "load_after",
     "Load Place Everywhere after Sim Settlements 2."),
]

# Playstyle -> mod assignments with priority and min hardware tier
# Format: (mod_name, priority, hardware_tier_min)
SKYRIM_PLAYSTYLE_MODS = {
    "vanilla-plus": [
        ("Unofficial Skyrim Special Edition Patch", 10, "low"),
        ("SSE Engine Fixes", 10, "low"),
        ("Address Library for SKSE Plugins", 10, "low"),
        ("SkyUI", 9, "low"),
        ("Static Mesh Improvement Mod", 7, "low"),
        ("A Quality World Map", 8, "low"),
        ("Cutting Room Floor", 6, "low"),
        ("Weapons Armor Clothing and Clutter Fixes", 8, "low"),
        ("Noble Skyrim Mod HD-2K", 5, "mid"),
        ("Realistic Water Two", 6, "low"),
    ],
    "survival": [
        ("Unofficial Skyrim Special Edition Patch", 10, "low"),
        ("SSE Engine Fixes", 10, "low"),
        ("Address Library for SKSE Plugins", 10, "low"),
        ("SkyUI", 9, "low"),
        ("Frostfall - Hypothermia Camping Survival", 9, "low"),
        ("Campfire - Complete Camping System", 9, "low"),
        ("Sunhelm Survival and Needs", 8, "low"),
        ("Hunterborn", 7, "low"),
        ("Wildcat - Combat of Skyrim", 6, "low"),
        ("Climates Of Tamriel", 5, "low"),
    ],
    "combat": [
        ("Unofficial Skyrim Special Edition Patch", 10, "low"),
        ("SSE Engine Fixes", 10, "low"),
        ("Address Library for SKSE Plugins", 10, "low"),
        ("SkyUI", 9, "low"),
        ("Valhalla Combat", 9, "low"),
        ("TK Dodge RE", 8, "low"),
        ("True Directional Movement", 9, "low"),
        ("Precision - Accurate Melee Collisions", 8, "low"),
        ("Ordinator - Perks of Skyrim", 6, "low"),
    ],
    "magic": [
        ("Unofficial Skyrim Special Edition Patch", 10, "low"),
        ("SSE Engine Fixes", 10, "low"),
        ("Address Library for SKSE Plugins", 10, "low"),
        ("SkyUI", 9, "low"),
        ("Apocalypse - Magic of Skyrim", 9, "low"),
        ("Mysticism - A Magic Overhaul", 8, "low"),
        ("Triumvirate - Mage Archetypes", 7, "low"),
        ("Odin - Skyrim Magic Overhaul", 7, "low"),
        ("Ordinator - Perks of Skyrim", 8, "low"),
    ],
    "visual": [
        ("Unofficial Skyrim Special Edition Patch", 10, "low"),
        ("SSE Engine Fixes", 10, "low"),
        ("Address Library for SKSE Plugins", 10, "low"),
        ("SkyUI", 9, "low"),
        ("Static Mesh Improvement Mod", 8, "low"),
        ("Skyrim Flora Overhaul", 7, "mid"),
        ("Noble Skyrim Mod HD-2K", 7, "mid"),
        ("Skyland AIO", 7, "mid"),
        ("Realistic Water Two", 8, "low"),
        ("Obsidian Weathers and Seasons", 8, "low"),
        ("Lux - Via", 6, "mid"),
        ("ENB Series - Rudy ENB", 5, "high"),
    ],
    "immersion": [
        ("Unofficial Skyrim Special Edition Patch", 10, "low"),
        ("SSE Engine Fixes", 10, "low"),
        ("Address Library for SKSE Plugins", 10, "low"),
        ("SkyUI", 9, "low"),
        ("Relationship Dialogue Overhaul", 8, "low"),
        ("Immersive Citizens - AI Overhaul", 8, "low"),
        ("Ordinator - Perks of Skyrim", 7, "low"),
        ("Interesting NPCs", 7, "low"),
        ("JK Skyrim", 6, "mid"),
        ("Cutting Room Floor", 7, "low"),
        ("Climates Of Tamriel", 5, "low"),
    ],
}

FALLOUT4_PLAYSTYLE_MODS = {
    "vanilla-plus": [
        ("Unofficial Fallout 4 Patch", 10, "low"),
        ("Full Dialogue Interface", 9, "low"),
        ("Improved Map with Visible Roads", 8, "low"),
        ("Armorsmith Extended", 7, "low"),
        ("Vivid Fallout - All in One", 6, "mid"),
        ("True Storms - Wasteland Edition", 5, "low"),
    ],
    "survival": [
        ("Unofficial Fallout 4 Patch", 10, "low"),
        ("Full Dialogue Interface", 9, "low"),
        ("Horizon", 9, "low"),
        ("Gas Masks of the Wasteland", 7, "low"),
        ("True Storms - Wasteland Edition", 6, "low"),
        ("Enhanced Blood Textures", 4, "low"),
    ],
    "settlement": [
        ("Unofficial Fallout 4 Patch", 10, "low"),
        ("Full Dialogue Interface", 9, "low"),
        ("Sim Settlements 2", 9, "low"),
        ("Workshop Framework", 8, "low"),
        ("Place Everywhere", 8, "low"),
        ("Spring Cleaning", 7, "low"),
    ],
    "combat": [
        ("Unofficial Fallout 4 Patch", 10, "low"),
        ("Full Dialogue Interface", 9, "low"),
        ("Arbitration - Combat AI", 8, "low"),
        ("Better Locational Damage", 8, "low"),
        ("Enhanced Blood Textures", 5, "low"),
        ("Armorsmith Extended", 6, "low"),
    ],
    "visual": [
        ("Unofficial Fallout 4 Patch", 10, "low"),
        ("Full Dialogue Interface", 9, "low"),
        ("Vivid Fallout - All in One", 8, "mid"),
        ("PhyLight - Physics based Relighting", 7, "mid"),
        ("True Storms - Wasteland Edition", 7, "low"),
    ],
    "sim-settlements": [
        ("Unofficial Fallout 4 Patch", 10, "low"),
        ("Full Dialogue Interface", 9, "low"),
        ("Sim Settlements 2", 10, "low"),
        ("Workshop Framework", 9, "low"),
        ("Place Everywhere", 7, "low"),
        ("Spring Cleaning", 6, "low"),
    ],
}
